name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cài đặt phụ thuộc backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e backend[dev]
      - name: Ruff
        run: python -m ruff check backend/app
      - name: Pytest
        run: pytest backend/tests

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Cài đặt dependencies
        run: |
          cd frontend
          npm install
      - name: Lint
        run: |
          cd frontend
          npm run lint
      - name: Kiểm thử
        run: |
          cd frontend
          npm run test
